version: "3.9"

services:
  postgres:
    image: postgres:17-alpine
    container_name: nest-postgres
    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: prashant
      POSTGRES_PASSWORD: prashant342
      POSTGRES_DB: kuicko-task-db

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nest_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: